### ISSUE TITLE
Server Index not updating

### ISSUE THREAD

**Issue by foola1** [openmultiplayer/web#336]
Hello!

Servers on the [list](https://open.mp/servers) are not updating. It would be very nice if open.mp can fix this because I have a little project looking at player counts over time but found data is abnormal for a few weeks.

Servers like ls-rp.com or red county roleplay are returning wrong for example

**Comment by Southclaws** [comment]
Hi, thanks for the report. The problem is likely around here if anyone wants to investigate:

https://github.com/openmultiplayer/web/blob/master/server/src/serverworker/serverworker.go#L43-L66

Though this was working on launch and hasn't really been touched since. What kinds of updates are you not seeing? The default update window is 30 seconds so it's not as instant as the sa-mp browser which directly queries the target server.

Are you seeing out of date information or servers that are offline appearing as online in the list?

**Comment by foola1** [comment]
Thanks for the reply, I think its both but I forgot which specific servers have gone offline but are showing online.

With out of date information, I will use example of Red County Rollerplay.
The server index will always say it has 4 players online which is not the case a lot of the time. The gamemode field is also different from the one displayed in the sa-mp browser. RC-RP 3.8.6 vs RC-RP 3.9.0.

With ls-rp.com I can see that there has been some change in player count over some days but it is not correct and is the same for a lot of the time. But, the gamemode name is correct between the server index and open.mp.

**Comment by Southclaws** [comment]
Updates are now fixed, the oldest entry is `Last updated about 2 hours ago` and all inactive servers have been removed.
