### ISSUE TITLE
Images in Contributing don't work

### ISSUE THREAD

**Issue by reusoo** [openmultiplayer/web#571]
![9](https://user-images.githubusercontent.com/73140302/161427646-f402bb1c-3799-4d55-93e3-0c0f8df9e257.jpg)https://open.mp/docs/meta/Contributing

**Comment by LeonardSSH** [comment]
The problem seems to be the URL to that image. Currently, the URL is set to  `../../frontend/public/images/contributing/edit-this-page.png`... which is wrong, because the assets are no longer in the frontend.

The solution would be to change all the URLs linked to the assets to the URL where all the assets are hosted. 

`../../frontend/public/images/contributing/edit-this-page.png` should be:
`https://assets.open.mp/assets/images/contributing/edit-this-page.png`

**Comment by Southclaws** [comment]
Simply removing the ../../frontend/public would fix it - the image replacement component adjusts the src url to use the cdn automatically.
