### ISSUE TITLE
Wrong preview for Skin ID 167

### ISSUE THREAD

**Issue by ReshiramZekrom1** [openmultiplayer/web#783]
The preview of skin ID 167 from the [official documentation](https://www.open.mp/docs/scripting/resources/skins) is wrong since it's actually a duplicate of skin ID 168.

This should be the right one:

<img src="https://i.ibb.co/jkLFR7c/167.png" alt="167" border="0">

**Comment by kkmzero** [comment]
I reported this 2 years ago #419 and if I remember correctly - it was fixed. I might be completely wrong because I don't know how you get these assets but if you have some kind of script synchronizing them, then that might explain why there's incorrect image again (same ID: 167). If I'm wrong, please forgive me, just trying to help out with additional information.

**Comment by akosd127** [comment]
https://assets.open.mp/assets/images/skins/167.png
Wrong image.

https://www.gtasamp.com.br/skins
All skins up to 299 can be found on this page in better quality and slightly brighter. Unfortunately, those added with SA-MP 0.3.7 RC3 from 300 to 311 are not available.

**Comment by NermanLegacy** [comment]
As of today, this has been resolved, thank you for reporting the issue!
